name: Test rclpy coverage
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: ros-tooling/setup-ros2@0.0.6
      - uses: ros-tooling/action-ros2-ci@0.0.10
        with:
          package-name: rclpy
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          fail_ci_if_error: false
      - uses: codecov/codecov-action@v1
        # Prevent being rate limited by only reporting coverage from the Ubuntu
        # build.
        if: matrix.os == 'ubuntu-18.04'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ros2_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: false
      - uses: actions/upload-artifact@master
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros2_ws/log
